on:
  push:
    paths:
      - .github/workflows/build.yml
      - src/**
      - include/**
      - xmake.lua
  pull_request:
  workflow_dispatch:

jobs:
  build-windows-x86_64:
    name: Build on Windows X86_64 (MSVC)
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1
        
    - name: Build BinaryStream Static (Debug)
      run: xmake config --mode=debug --kind=static && xmake --all

    - name: Build BinaryStream Shared (Debug)
      run: xmake config --mode=debug --kind=shared && xmake --all
      
    - name: Build BinaryStream Static (Release)
      run: xmake config --mode=release --kind=static && xmake --all

    - name: Build BinaryStream Shared (Release)
      run: xmake config --mode=release --kind=shared && xmake --all

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BinaryStream-windows-x86_64-${{ github.sha }}
        path: artifacts/BinaryStream-windows-x86_64.zip

  build-windows-arm64:
    name: Build on Windows ARM64 (MSVC)
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: arm64

    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1
        
    - name: Build BinaryStream Static (Debug)
      run: xmake config --mode=debug --arch=arm64 --kind=static && xmake --all

    - name: Build BinaryStream Shared (Debug)
      run: xmake config --mode=debug --arch=arm64 --kind=shared && xmake --all
      
    - name: Build BinaryStream Static (Release)
      run: xmake config --mode=release --arch=arm64 --kind=static && xmake --all

    - name: Build BinaryStream Shared (Release)
      run: xmake config --mode=release --arch=arm64 --kind=shared && xmake --all

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BinaryStream-windows-arm64-${{ github.sha }}
        path: artifacts/BinaryStream-windows-arm64.zip

  build-linux:
    name: Build on Linux X86_64 (Clang)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Clang
      run: |
        sudo apt-get update && sudo apt-get install -y clang
        sudo apt-get update
        sudo apt-get install -y clang libc++-dev libc++abi-dev
      
    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1
        
    - name: Build BinaryStream Static (Debug)
      run: xmake config --mode=debug --kind=static && xmake --all

    - name: Build BinaryStream Shared (Debug)
      run: xmake config --mode=debug --kind=shared && xmake --all
      
    - name: Build BinaryStream Static (Release)
      run: xmake config --mode=release --kind=static && xmake --all

    - name: Build BinaryStream Shared (Release)
      run: xmake config --mode=release --kind=shared && xmake --all

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BinaryStream-linux-x86_64-${{ github.sha }}
        path: artifacts/BinaryStream-linux-x86_64.zip

  build-macos:
    name: Build on MacOS ARM64 (Clang)
    runs-on: macos-14
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Ensure Command Line Tools
      run: |
        xcode-select --install 2>/dev/null || true

    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: Build BinaryStream Static (Debug)
      run: xmake config --mode=debug --kind=static && xmake --all

    - name: Build BinaryStream Shared (Debug)
      run: xmake config --mode=debug --kind=shared && xmake --all

    - name: Build BinaryStream Static (Release)
      run: xmake config --mode=release --kind=static && xmake --all

    - name: Build BinaryStream Shared (Release)
      run: xmake config --mode=release --kind=shared && xmake --all

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BinaryStream-macosx-arm64-${{ github.sha }}
        path: artifacts/BinaryStream-macosx-arm64.zip